version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16.8.0
      - image: neo4j:4.4.2
        environment:
          NEO4J_AUTH: none
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint checks
          command: npm run lint-check
      - run:
          name: Unit tests
          command: npm run unit-test
      - run:
          name: Integration tests
          command: npm run int-test
      - run:
          name: End-to-end tests
          command: npm run e2e-test
