version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
      - image: neo4j:3.5.12
        environment:
          NEO4J_AUTH: none
    steps:
      - checkout
      - run: npm install
      - run: npm run checks
      - run: npm run int-test
