version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.14.1
      - image: neo4j:3.5.12
        environment:
          NEO4J_AUTH: none
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint checks
          command: npm run lint-check
      - run:
          name: Unit tests
          command: npm run unit-test
      - run:
          name: Integration tests
          command: npm run int-test
