version: '3'
services:
    neo4j:
        container_name: neo4j-test
        image: neo4j:4.2.7
        environment:
            - NEO4J_AUTH=none
        ports:
            - '7474:7474'
            - '7687:7687'
