version: '3'
services:
    neo4j:
        container_name: neo4j
        image: neo4j:5.16.0
        environment:
            - NEO4J_AUTH=none
        ports:
            - '7474:7474'
            - '7687:7687'
