const AWARD = 'AWARD';
const AWARD_CEREMONY = 'AWARD_CEREMONY';
const AWARD_CEREMONY_CATEGORY = 'AWARD_CEREMONY_CATEGORY';
const CHARACTER = 'CHARACTER';
const CHARACTER_GROUP = 'CHARACTER_GROUP';
const COMPANY = 'COMPANY';
const CREATIVE_CREDIT = 'CREATIVE_CREDIT';
const CREW_CREDIT = 'CREW_CREDIT';
const FESTIVAL = 'FESTIVAL';
const FESTIVAL_SERIES = 'FESTIVAL_SERIES';
const MATERIAL = 'MATERIAL';
const NOMINATION = 'NOMINATION';
const PERSON = 'PERSON';
const PRODUCER_CREDIT = 'PRODUCER_CREDIT';
const PRODUCTION = 'PRODUCTION';
const PRODUCTION_IDENTIFIER = 'PRODUCTION_IDENTIFIER';
const REVIEW = 'REVIEW';
const ROLE = 'ROLE';
const SEASON = 'SEASON';
const VENUE = 'VENUE';
const WRITING_CREDIT = 'WRITING_CREDIT';

const ACTIONS = {
	CREATE: 'CREATE',
	EDIT: 'EDIT',
	UPDATE: 'UPDATE',
	DELETE: 'DELETE',
	SHOW: 'SHOW'
};

const CREDIT_TYPES = {
	NON_SPECIFIC_SOURCE_MATERIAL: 'NON_SPECIFIC_SOURCE_MATERIAL',
	RIGHTS_GRANTOR: 'RIGHTS_GRANTOR'
};

const MODELS = {
	[AWARD]: AWARD,
	[AWARD_CEREMONY]: AWARD_CEREMONY,
	[AWARD_CEREMONY_CATEGORY]: AWARD_CEREMONY_CATEGORY,
	[CHARACTER]: CHARACTER,
	[CHARACTER_GROUP]: CHARACTER_GROUP,
	[COMPANY]: COMPANY,
	[CREATIVE_CREDIT]: CREATIVE_CREDIT,
	[CREW_CREDIT]: CREW_CREDIT,
	[FESTIVAL]: FESTIVAL,
	[FESTIVAL_SERIES]: FESTIVAL_SERIES,
	[MATERIAL]: MATERIAL,
	[NOMINATION]: NOMINATION,
	[PERSON]: PERSON,
	[PRODUCER_CREDIT]: PRODUCER_CREDIT,
	[PRODUCTION]: PRODUCTION,
	[PRODUCTION_IDENTIFIER]: PRODUCTION_IDENTIFIER,
	[REVIEW]: REVIEW,
	[ROLE]: ROLE,
	[SEASON]: SEASON,
	[VENUE]: VENUE,
	[WRITING_CREDIT]: WRITING_CREDIT
};

const MODEL_TO_NODE_LABEL_MAP = {
	[AWARD]: 'Award',
	[AWARD_CEREMONY]: 'AwardCeremony',
	[CHARACTER]: 'Character',
	[COMPANY]: 'Company',
	[FESTIVAL]: 'Festival',
	[FESTIVAL_SERIES]: 'FestivalSeries',
	[MATERIAL]: 'Material',
	[PERSON]: 'Person',
	[PRODUCTION]: 'Production',
	[SEASON]: 'Season',
	[VENUE]: 'Venue'
};

export {
	ACTIONS,
	CREDIT_TYPES,
	MODELS,
	MODEL_TO_NODE_LABEL_MAP
};
