const AWARD = 'AWARD';
const AWARD_CEREMONY = 'AWARD_CEREMONY';
const CHARACTER = 'CHARACTER';
const CHARACTER_GROUP = 'CHARACTER_GROUP';
const COMPANY = 'COMPANY';
const CREATIVE_CREDIT = 'CREATIVE_CREDIT';
const CREW_CREDIT = 'CREW_CREDIT';
const MATERIAL = 'MATERIAL';
const PERSON = 'PERSON';
const PRODUCER_CREDIT = 'PRODUCER_CREDIT';
const PRODUCTION = 'PRODUCTION';
const ROLE = 'ROLE';
const VENUE = 'VENUE';
const WRITING_CREDIT = 'WRITING_CREDIT';

const CREDIT_TYPES = {
	NON_SPECIFIC_SOURCE_MATERIAL: 'NON_SPECIFIC_SOURCE_MATERIAL',
	RIGHTS_GRANTOR: 'RIGHTS_GRANTOR'
};

const MODELS = {
	[AWARD]: AWARD,
	[AWARD_CEREMONY]: AWARD_CEREMONY,
	[CHARACTER]: CHARACTER,
	[CHARACTER_GROUP]: CHARACTER_GROUP,
	[COMPANY]: COMPANY,
	[CREATIVE_CREDIT]: CREATIVE_CREDIT,
	[CREW_CREDIT]: CREW_CREDIT,
	[MATERIAL]: MATERIAL,
	[PERSON]: PERSON,
	[PRODUCER_CREDIT]: PRODUCER_CREDIT,
	[PRODUCTION]: PRODUCTION,
	[ROLE]: ROLE,
	[VENUE]: VENUE,
	[WRITING_CREDIT]: WRITING_CREDIT
};

const MODEL_TO_NODE_LABEL_MAP = {
	[AWARD]: 'Award',
	[AWARD_CEREMONY]: 'AwardCeremony',
	[CHARACTER]: 'Character',
	[COMPANY]: 'Company',
	[MATERIAL]: 'Material',
	[PERSON]: 'Person',
	[PRODUCTION]: 'Production',
	[VENUE]: 'Venue'
};

export {
	CREDIT_TYPES,
	MODELS,
	MODEL_TO_NODE_LABEL_MAP
};
