const CREDIT_TYPES = {
	ORIGINAL_VERSION: 'ORIGINAL_VERSION',
	NON_SPECIFIC_SOURCE_MATERIAL: 'NON_SPECIFIC_SOURCE_MATERIAL'
};

const IRREGULAR_PLURAL_NOUNS_MAP = {
	person: 'people'
};

export {
	CREDIT_TYPES,
	IRREGULAR_PLURAL_NOUNS_MAP
};
